//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientContact = new HashSet<ClientContact>();
            this.LoyaltyPointMovement = new HashSet<LoyaltyPointMovement>();
            this.Order = new HashSet<Order>();
        }
    
        public int ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ClientTypeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LegalAddress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string OGRN { get; set; }
        public string BankName { get; set; }
        public string BankBIC { get; set; }
        public string BankAccount { get; set; }
        public string CorrespondentAccount { get; set; }
        public int DeliveryAreaId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int LoyaltyPoints { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual ClientType ClientType { get; set; }
        public virtual DeliveryArea DeliveryArea { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientContact> ClientContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoyaltyPointMovement> LoyaltyPointMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
