//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.MovementProduct = new HashSet<MovementProduct>();
            this.Order = new HashSet<Order>();
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int PositionId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> FireDate { get; set; }
        public string DriverLicenseNumber { get; set; }
        public Nullable<System.DateTime> DriverLicenseExpiration { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual EmployeePosition EmployeePosition { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovementProduct> MovementProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
