//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementProduct
    {
        public int MovementId { get; set; }
        public int MovementTypeId { get; set; }
        public Nullable<int> SourceWarehouseId { get; set; }
        public Nullable<int> DestinationWarehouseId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime MovementDate { get; set; }
        public string Notes { get; set; }
        public int ResponsibleEmployeeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual MovementType MovementType { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
