//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> WaterSourceId { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> AssignedEmployeeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
        public virtual WaterSource WaterSource { get; set; }
    }
}
