//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderItem = new HashSet<OrderItem>();
            this.StockProduct = new HashSet<StockProduct>();
        }
    
        public int ProductId { get; set; }
        public string Article { get; set; }
        public string ProductName { get; set; }
        public int ProductTypeId { get; set; }
        public string Description { get; set; }
        public int UnitId { get; set; }
        public decimal DefaultPrice { get; set; }
        public Nullable<int> WaterTypeId { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> MinStockLevel { get; set; }
        public Nullable<decimal> MaxStockLevel { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual WaterType WaterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockProduct> StockProduct { get; set; }
    }
}
