//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterDelivery.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int VehicleId { get; set; }
        public int VehicleTypeId { get; set; }
        public int ModelId { get; set; }
        public string LicensePlate { get; set; }
        public int Year { get; set; }
        public string VIN { get; set; }
        public Nullable<decimal> TankCapacity { get; set; }
        public Nullable<int> CurrentMileage { get; set; }
        public string FuelType { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> GarageId { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Garage Garage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Status Status { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
